config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "pages#home"
  root to: 'lists#index'
  resources :lists, only: [:index, :new, :show, :create, :destroy] do
    resources :bookmarks, only: [:create, :new, :destroy]
    resources :reviews, only: %i[new create]
  end
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_associated :movie, uniqueness: true
  validates_associated :list, uniqueness: true
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true
  validates :name, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @movie = Movie.find(params[:bookmark][:movie_id])
    @list = List.find(params[:list_id])

    @bookmark.movie = @movie
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]
  def index
    @lists = List.all
  end

  def show
    @review = Review.new
    @bookmarks = @list.bookmarks
    # @movies = @list.movies
  end

  def new
    @list = List.new(params[:list_id])
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id]) # lists/n
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_list, except: [:destroy]

  # def new
  #   @review = Review.new
  # end

  def create
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render "lists/show"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
  end

  private

  def find_list
    @list = List.find(params[:list_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<div class = "container">
  <div class="card mt-3 p-5">
  <h1>Add a Comment to your <%= @list.name %> list</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <div class="row">
      <%= f.input :comment %>
      <%= f.association :movie %>
    </div>
    <div class="row">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
  <%= link_to "Go Back", list_path(@list), class: "link-primary mt-3" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="turbolinks-cache-control" content="no-cache">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.6)), url(https://images.hdqwalls.com/wallpapers/final-fantasy-xv-artwork-h5.jpg);">
  <div class="container">
    <h1>Tired of looking for movies with the same atmosphere?</h1>
    <h2><span data-controller="typed-js"></span></h2>
    <h3 class="mt-2" style="display: inline;"> There are currently <span class="badge badge-light"><%=  @lists.count %></span> lists</h3>
    <%= link_to "Add a list", new_list_path, class: "btn btn-outline-light btn-lg rounded-pill", style: "margin-left: 20px" %>
  </div>
</div>
<div class = "main-container-index">
  <div class = "cards-index" style="align-items: center; justify-content: space-between">
    <% @lists.each do |list| %>
      <% if list.photo.attached? %>
        <%#= link_to "🗑", list_path(list), method: :delete %>
        <a href="<%= list_path(list) %>" style="display: block; text-decoration: none">
          <div class="card-index" style="background-image: url('<%= cl_image_path list.photo.key %>')">
            <%= list.name %>
            <%#= link_to list.name, list_path(list) %>
          </div>
        </a>
        <%#= link_to "🗑", list_path(list), method: :delete %>
      <% else %>
        <a href="<%= list_path(list) %>" style="display: block; text-decoration: none">
          <div class="card-index" style="background-image: url('https://images.hdqwalls.com/wallpapers/final-fantasy-xv-artwork-h5.jpg')">
            <%= list.name %>
          </div>
        </a>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class = "container">
  <div class="card mt-3 p-5">
  <h1>Add a List</h1>
  <%= simple_form_for @list do |f| %>
    <div class="row">
      <%= f.input :name %>
    </div>
    <div class="row">
      <%= f.input :photo, as: :file %>
    </div>
    <div class="row">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
  <%= link_to "Go Back", lists_path, class: "link-primary mt-3" %>
  </div>
</div>

app/views/lists/show.html.erb
<% if @list.photo.attached? %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),  rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>'); background-position: center;">
    <div class="container">
      <h1><%= @list.name %></h1>
      <div class="btn btn-outline-light btn-lg rounded-pill"> <%= @list.movies.count %> <%= @list.movies.count > 1 ? "movies" : "movie"%> in this list</div>
    </div>
  </div>
<% else %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),  rgba(0,0,0,0.3)), url('https://images.hdqwalls.com/wallpapers/final-fantasy-xv-artwork-h5.jpg'); background-position: center;">
    <div class="container">
      <h1><%= @list.name %></h1>
    </div>
  </div>
<% end %>
<div class="container pt-3">
  <%= link_to "Create a Bookmark", new_list_bookmark_path(@list), class: "btn btn-outline-primary", type: "button", style: "display: inline;"%>
  <%= link_to "Delete This List", list_path(@list), class: "btn btn-outline-danger", method: :delete %>
</div>
<div class="main-container-index mt-2">
  <div class = "cards-index">
    <% if @bookmarks.any?%>
      <% @bookmarks.each do |bookmark| %>
        <% movie = Movie.find(bookmark.movie_id)%>
        <div class="card" style="width: 18rem; justify-content: space-around; align-items: center; display: flex">
          <img class="card-img-top" src="<%= movie.poster_url %>" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title"><%= movie.title %></h5>
            <p class="card-text"><%= movie.overview %></p>
            <p class="card-text"><%= movie.rating %> ⭐️</p>
            <h4>Comments:</h4>
            <p><%= bookmark.comment %></p>
            <%= link_to "Delete Bookmark", list_bookmark_path(@list, bookmark), method: :delete, class: "btn btn-outline-danger", data: { confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <h1> No Bookmarks in this list yet, add some!</h1>
    <% end %>
  </div>
  <div class="card p-4" style="width: 20rem; display: flex">
    <h6 style="font-weight: bold">Add a Review to your <%= @list.name %> List</h6>
    <%= simple_form_for [@list, @review] do |f| %>
      <%= f.input :content %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
    <hr>
    <h6 sty;e = "text-align: left">Reviews:</h6>
    <% if @list.reviews.any? %>
      <% @list.reviews.each do |review| %>
        <P><%= review.content %></p>
        <div class="right-side"><%= link_to "🗑", review_path(review), method: :delete %></div>
      <% end %>
    <% else %>
      <p>There are no reviews</p>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="outer-footer">
    <h4>This website is made with resentment at LeWagon ♡</h4>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light px-3">
  <span class="navbar-brand mb-0 h1"><%= link_to "WatchHobo", lists_path %></span>
  <div class="right-side">
    <%# <span><%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary", type: "button" %>
  </div>
</nav>